### PR TITLE
added ability to pass runtime limit to start_parallel_jobs_slurm.py

### LINKED ISSUE #2017: Add --time option to start_parallel_jobs_slurm.py

### PR DESCRIPTION
**Pull request by gregcaporaso**
fixes #2017. 

This includes the commits in #2019, just adds a couple of related clean-ups.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
I tested this on monsoon (NAU cluster) with different combinations of specifying ``--time``, specifying in ``qiime_config``, not specifying (so falling back to the system default) and all works as expected. 

Thanks again @mkgilbert, we'll merge this when the tests pass (shouldn't be an issue, as they passed last night and none of my changes would trigger any differences).

**Comment by mkgilbert** [comment]
That's good news! You're very welcome and thank you for the opportunity!

**Comment by jairideout** [comment]
Only comment is to add a description of this new setting in the QIIME config docs.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1639/

**Pull request merged**
