### PR TITLE
BUG: update minimum required versions of two deps

### LINKED ISSUE #1972: update minimum version of ``qiime-default-reference`` to 0.1.2...
... when that release goes live. See bug description on biocore/qiime-default-reference#14.

### PR DESCRIPTION
**Pull request by jairideout**
Updated to qiime-default-reference 0.1.2 and scikit-bio 0.2.3.

Fixes #1972.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Looks good, ready for merge when tests pass.

**Comment by gregcaporaso** [comment]
There is a failure from one of the parallel chimera slayer tests, though the serial ones are passing. I can look into this... 

```
Testing /mnt/workspace/qiime-github-pr/qiime/tests/test_parallel/test_identify_chimeric_seqs.py:

test_parallel_chimeric_sequence_identifier_blast_fragments (__main__.ParallelChimericSequenceIdentifierTests)
Test ParallelChimericSequenceIdentifier using blast_fragments. ... ok
test_parallel_chimeric_sequence_identifier_chimera_slayer (__main__.ParallelChimericSequenceIdentifierTests)
Test ParallelChimericSequenceIdentifier using ChimeraSlayer. ... FAIL

======================================================================
FAIL: test_parallel_chimeric_sequence_identifier_chimera_slayer (__main__.ParallelChimericSequenceIdentifierTests)
Test ParallelChimericSequenceIdentifier using ChimeraSlayer.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/workspace/qiime-github-pr/qiime/tests/test_parallel/test_identify_chimeric_seqs.py", line 123, in test_parallel_chimeric_sequence_identifier_chimera_slayer
    self.assertEqual(len(results), 1)
AssertionError: 5 != 1

----------------------------------------------------------------------
Ran 2 tests in 114.378s

FAILED (failures=1)
```

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1610/

**Comment by gregcaporaso** [comment]
I did a few tests of this, and the number of chimeras that comes back seems to be stochastic. In the jenkins this test got five chimeras, in my test on AWS four chimeras were found, and [we observed changes in this value in the past with changes to the PyNAST reference alignment](https://github.com/biocore/qiime/commit/9f7bb2ae9798e6ed3fc4e6fd58c014fd37c2f2a3). 

How should we handle this? I'm thinking that we test that this file isn't empty, as this is intended to just be a sanity check of the parallel wrapper at this stage and ``test_identify_chimeric_seqs.py`` has more extensive testing.

**Comment by wasade** [comment]
Seems reasonable

**Comment by gregcaporaso** [comment]
@jairideout, let me know when this one is ready for re-review.

**Comment by jairideout** [comment]
@gregcaporaso I just pushed a fix for the failing test.

**Comment by gregcaporaso** [comment]
Looks good, ready for merge when tests pass.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1611/

**Pull request merged**
