### PR TITLE
Fix group significance documentation typos

### PR DESCRIPTION
**Pull request by gblanchard4**
I fixed a few typos on the `group_significance.py` documentation. It's nothing major, just things I noticed whenever I was reading it over. I know you guys are not making any major changes to Qiime1, but I figured a documentation fix wouldn't hurt.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by gregcaporaso** [comment]
Ok to test.

**Comment by gregcaporaso** [comment]
Thanks @gblanchard4. We'll merge this if the tests pass.

**Comment by gregcaporaso** [comment]
ok to test

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1721/

**Pull request merged**
