### PR TITLE
DOC: updates to 454 overview tutorial

### LINKED ISSUE #1886: update help text at bottom of the workflow index pages
The text:

```
Need help?
You can get answers to your questions on the QIIME Forum.
See the QIIME tutorials for examples of additional analyses that can be run.
You can find documentation of the QIIME scripts in the QIIME script index.
```

should be replaced with:

```
Need help? See http://help.qiime.org. 
```

### PR DESCRIPTION
**Pull request by jairideout**
@gregcaporaso and I "pair-programmed" this. 

Fixes #1886.

This PR contains all of the commits in #1893, so closing that in favor of this one.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1557/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1558/

**Comment by gregcaporaso** [comment]
Thanks @jairideout - I'll review ASAP. I pulled your changes, so I'll make edits directly.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1561/

**Comment by gregcaporaso** [comment]
@jairideout and I reviewed locally. This is ready to go.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1572/

**Pull request merged**
