### PR TITLE
BUG FIX PARTAY!!

### LINKED ISSUE #1870: Non-unique files/folders written in temp directory (analysis runs fail with multiple users)
I have Qiime 1.8 and Qiime 1.9rc1 in a server having multiple users. Qiime seems to write non-unique files to tmp folder (/tmp by default). For example, user A is running Qiime which writes /tmp/R.stdout file. Now, user B is running Qiime and it is trying to write /tmp/R.stdout, but it fails because the file already exists and it is owner by user A.

### PR DESCRIPTION
**Pull request by jairideout**
Fixes #1870 #1873 #1875 #1879.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
jai right now

**Comment by jairideout** [comment]
So fitting...

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1539/

**Comment by jairideout** [comment]
@gregcaporaso tests are passing, can you please review?

**Comment by gregcaporaso** [comment]
This looks good, thanks @jairideout!

**Pull request merged**
