### PR TITLE
DOC: updates install instructions to use conda

### PR DESCRIPTION
**Pull request by gregcaporaso**
this was written in collaboration with @cuttlefishh.

replaces #2164, #2162

### CODE REVIEW

**Comment by cuttlefishh** [comment]
Thanks, Greg. I had a look at the website and it seems the HTML formatting did not work quite right. http://qiime.org/install/index.html

**Comment by ebolyen** [comment]
We're working on fixing that, should be correct in a few minutes.

**Comment by gregcaporaso** [comment]
Fixed now, thanks!

**Comment by cuttlefishh** [comment]
Thanks. Formatting looks good. However the usage of "Conda", "Miniconda", and "Anaconda" is a bit convoluted now. Can you please make it consistent? I favor the use of "Conda" to describe Conda generally, and "Miniconda" to describe the installation. We thought Miniconda was preferable to Anaconda due to the smaller download. But whichever you want -- I would just make it consistent.

**Comment by gregcaporaso** [comment]
I agree it's a bit confusing. What I was going for here was that Anaconda
is the name of the project, Miniconda is essentially a version of it, and
conda is the name of the executable. I'll take a pass at cleaning it up,
but I can't get to it today.

**Comment by cuttlefishh** [comment]
Ok sounds good. Thanks!

**Comment by cuttlefishh** [comment]
Minor point: for consistency of headings, let's delete the period from Step 2 and Step 3.

**Comment by cuttlefishh** [comment]
@gregcaporaso Do you also want to write a post about the new instructions on the QIIME 1 Forum and "pin" it to the top?

**Comment by gregcaporaso** [comment]
That's a good idea, I'll do that now.

**Comment by gregcaporaso** [comment]
@cuttlefishh, I addressed the two suggestions you brought up here (*Anaconda* -> *Miniconda* for clarity, and removing periods from the titles of steps 2 and 3). Took me a little while because I was leaving on a trip right when you made the suggestions.

**Comment by cuttlefishh** [comment]
Thanks! Looks good.  #qiime1forever

**Comment by gregcaporaso** [comment]
> #qiime1forever

Noooooooo!!!!!

**Pull request merged**
