### PR TITLE
Improvement in split_libraries_lea_seq.py

### PR DESCRIPTION
**Pull request by charudatta-navare**
removed deprecated function parse_fastq, and changed it to skbio.io.read
made sure meaningful errors are given when unexpected optional arguments are supplied

### CODE REVIEW

**Comment by jairideout** [comment]
Thanks @charudatta-navare! Can you please revert back to using the deprecated `parse_fasta`/`parse_fastq` parsers? See @gregcaporaso's comment [here](https://github.com/biocore/qiime/pull/1726#issuecomment-67854768) for why we'd like to keep using the old parsers for 1.9.0.

**Comment by charudatta-navare** [comment]
Thanks for letting me know - I will make the changes tomorrow.
@jairideout

**Comment by jairideout** [comment]
Thanks!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1540/

**Comment by charudatta-navare** [comment]
Made the changes, @cleme @jairideout. Have a look!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1541/

**Comment by jairideout** [comment]
Thanks! There are merge conflicts, can you please fix?

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1547/

**Pull request closed without merging**
