### PR TITLE
Update split_libraries.py

### PR DESCRIPTION
**Pull request by aubreybailey**
error messages suggest using a non-existent script

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by jairideout** [comment]
ok to test

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1662/

**Comment by ElDeveloper** [comment]
Thanks @aubreybailey

**Pull request merged**
