### PR TITLE
Otu gradient correlation

### PR DESCRIPTION
**Pull request by Cody-Glickman**

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by gregcaporaso** [comment]
OK to test.

**Comment by josenavas** [comment]
I though new functionality is not going to be added to qiime 1.X series?

**Comment by wdwvt1** [comment]
@cody-glickman - this feature has been added as
'observation_metadata_correlation.py'. I think what you pushed were just
old commits on the branch I was working on for that feature. If there was
new functionality in there please add a new pr.

**Pull request closed without merging**
