### PR TITLE
DOC: update parallel QIIME tutorial

### LINKED ISSUE #1867: Add a note describing the benefits of using HDF5
Since HDF5 is optional and users may wonder whether or not they'll want to use this dependency, we should provide a small description about the benefits and reasons why you might want to use HDF5 instead of JSON. Not sure where this should be in the documentation.

### LINKED ISSUE #1870: Non-unique files/folders written in temp directory (analysis runs fail with multiple users)
I have Qiime 1.8 and Qiime 1.9rc1 in a server having multiple users. Qiime seems to write non-unique files to tmp folder (/tmp by default). For example, user A is running Qiime which writes /tmp/R.stdout file. Now, user B is running Qiime and it is trying to write /tmp/R.stdout, but it fails because the file already exists and it is owner by user A.

### PR DESCRIPTION
**Pull request by jairideout**
Fixes #1867 #1870.

@gregcaporaso can you please review?

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1564/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1566/

**Comment by gregcaporaso** [comment]
@jairideout and I reviewed locally. This is good to go.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1569/

**Pull request merged**
