### PR TITLE
Mnt remove pylab imports in favor of `pyplot`

### PR DESCRIPTION
**Pull request by tacaswell**
Convert use of `pylab` to `matplotlib.pyplot`.  pylab is intended for interactive use, not in scripts/libraries. We are also trying to discourage the use of the `pylab` namespace (but will never actually deprecate it).

There is also someone squating on pylab on pypi (https://pypi.python.org/pypi/pylab) which can cause confusion for your users which shows up on the mpl mailing lists.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by jairideout** [comment]
Thanks @tacaswell!

**Comment by jairideout** [comment]
ok to test

**Comment by tacaswell** [comment]
That is an interesting CI bot setup you have.  PRs from random people need to be signed off on to trigger the build?

**Comment by jairideout** [comment]
Yep, we're using Jenkins on EC2 to test QIIME, it's not possible with Travis.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1706/

**Comment by tacaswell** [comment]
I will try to get to fixing your other mpl issues tonight

**Comment by tacaswell** [comment]
Is there anyway to get your CI to build on every push?  I do not have py2 dev enviroment set up anywhere.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1707/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1708/

**Comment by tacaswell** [comment]
```

======================================================================
FAIL: test_draw_pcoa_graph (__main__.TopLevelTests)
draw_pcoa_graph: draws the matplotlib figure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/workspace/qiime-github-pr/qiime/tests/test_make_2d_plots.py", line 241, in test_draw_pcoa_graph
    self.assertEqual(obs1, expsrcmap2 + expimgmap2)
AssertionError: '<img src="/tmp/PC1_vs_PC2_plot.png" border="0" ismap usemap="#pointsSampleID12" width="360" height="360" />\n\n<MAP name="pointsSampleID12">\n<AREA shape="circle" coords="100,276,5" href="#Sample1: Day1"  onmouseover="return overlib(\'Sample1: Day1\');" onmouseout="return nd();">\n<AREA shape="circle" coords="279,68,5" href="#Sample2: Day1"  onmouseover="return overlib(\'Sample2: Day1\');" onmouseout="return nd();">\n\n</MAP>\n' != '<img src="/tmp/PC1_vs_PC2_plot.png" border="0" ismap usemap="#pointsSampleID12" width="360" height="360" />\n\n<MAP name="pointsSampleID12">\n<AREA shape="circle" coords="100,208,5" href="#Sample1: Day1"  onmouseover="return overlib(\'Sample1: Day1\');" onmouseout="return nd();">\n<AREA shape="circle" coords="279,84,5" href="#Sample2: Day1"  onmouseover="return overlib(\'Sample2: Day1\');" onmouseout="return nd();">\n\n</MAP>\n'

----------------------------------------------------------------------
Ran 11 tests in 1.976s
```

Is this a standing failure or something I caused?  I spent ~5min trying to trace it back and quickly got lost in the many function calls.

**Comment by tacaswell** [comment]
The difference is in the coordinate of the location of the point

```diff
In [20]: print('\n'.join(list(d.compare(a.split('\n'), b.split('\n')))))
  <img src="/tmp/PC1_vs_PC2_plot.png" border="0" ismap usemap="#pointsSampleID12" width="360" height="360" />
  
  <MAP name="pointsSampleID12">
- <AREA shape="circle" coords="100,276,5" href="#Sample1: Day1"  onmouseover="return overlib('Sample1: Day1');" onmouseout="return nd();">
?                                   ^^

+ <AREA shape="circle" coords="100,208,5" href="#Sample1: Day1"  onmouseover="return overlib('Sample1: Day1');" onmouseout="return nd();">
?                                   ^^

- <AREA shape="circle" coords="279,68,5" href="#Sample2: Day1"  onmouseover="return overlib('Sample2: Day1');" onmouseout="return nd();">
?                                  -

+ <AREA shape="circle" coords="279,84,5" href="#Sample2: Day1"  onmouseover="return overlib('Sample2: Day1');" onmouseout="return nd();">
?                                   +

  
  </MAP>
  
```

**Comment by tacaswell** [comment]
ok, I definitely broke that...

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1709/

**Comment by tacaswell** [comment]
failures are in `otu` and `stats` neither of which I think I caused.

**Comment by gregcaporaso** [comment]
@tacaswell, thanks a lot for your help with this. At this point, we're only planning critical bug fix releases of QIIME 1, and have entirely shifted our efforts to QIIME 2 development (some details [here](http://americangut.org/qiime-2-will-revolutionize-microbiome-bioinformatics/)). Much of the QIIME 1 code base is outdated and less than ideal, definitely including our use of matplotlib, which is why we're focusing our developer time on a complete re-write with QIIME 2. So, while we *really* appreciate your input on this, we don't want you to waste your time trying to help us fix this version as (ideally) there won't be anymore QIIME 1 releases. We would love to get your input on QIIME 2 and scikit-bio down the road though, if you're interested in contributing there.

Given that there aren't going to be future versions of QIIME 1, do you think a matplotlib version cap would be an issue? We realize we wouldn't get any new versions of matplotlib, but that's ok with us in this instance since there won't be new versions of QIIME 1.

**Comment by tacaswell** [comment]
Fair enough.  Sorry for showing up and crashing around in your code base with minimal context :smiling_imp: .

The bug with 1.5.0 is due to an interesting corner case that we should deal with upstream (creating a figure legend in a different figure than the artist you are creating a the legend entry from), discovering that was probably worth my time so I have no regrets.

I would like it if the pylab -> pyplot stuff got in just in case there is another release due to the issue with a `pylab` squatter on pypi.  

If QIIME1 is completely in maintenance mode then a version cap is reasonable,  but I think I have it working again.

I would be happy to provide feed back on plotting related issues in QIIME 2.  I can not commit serious development time, but can help with review/suggestions.  Please also hit the mpl mailing lists as often as you need.  Interaction with down-stream projects is something that mpl should get better about.

**Comment by gregcaporaso** [comment]
@tacaswell, glad that you got something useful out of this too! @jairideout and I just did some local tests, and this all looks good, so we're going to merge. We really appreciate your help with this, so thanks again!

**Comment by jairideout** [comment]
We also added a prominent note to our README.md and CONTRIBUTING.md letting devs know that this project is in maintenance mode, and recommending that devs contribute to QIIME 2 going forward. Sorry that wasn't clear @tacaswell, hopefully this will help avoid confusion in the future. Thanks again!

**Pull request merged**
