### PR TITLE
Modified multiple_split_libraries_fastq.py to filter target files, wi…

### PR DESCRIPTION
**Pull request by walterst**
…th wildcard option, to address issue #1971

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1681/

**Comment by gregcaporaso** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1717/

**Comment by gregcaporaso** [comment]
@walterst, this is ancient, but we finally got jenkins back to passing, so we're reviewing some of these old PRs. This one is passing its script usage tests - want to fix that? Or if you don't think this is relevant anymore, let me know and I can close the PR. Your call.

**Comment by walterst** [comment]
Added changes to fix script usage tests, and further clarity/defaults in the option's text.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1720/

**Pull request merged**
