### PR TITLE
Fix issue #1830

### LINKED ISSUE #1830: --minimum_failure_threshold not properly implemented
Within the script pick_open_reference_otus.py the --minimum_failure_threshold is properly described in the documentation to decide whether or not to do steps 2 and 3 (or skip right to steps 4) by comparing this threshold (default being set to 100,000 which by the way is not included in the documentation) to the **number of sequences failing the reference picking step**. However, the threshold is improperly compared to the **number of subsampled sequences**. 

This bug causes the pipeline to skip steps 2 and 3 when the defaults are used even with very large datasets (e.g. 5 million failed reads are attempted to be de novo otu picked in step 4). 

A PR will be issued shortly to address this.

### PR DESCRIPTION
**Pull request by mlangill**
Fixes the application of the --minimum_failure_threshold and creation of the subsampling failures file till after step2 begins. Fixes #1830

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Thanks @mlangill! Have you tested the script on a real data set following both paths through the code (i.e., include steps 2 and 3, and excluding steps 2 and 3)? 

@ekopylova, do you have time to run that same test as well with this branch?

**Comment by ekopylova** [comment]
Yes, I can test this branch as well.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1514/

**Comment by gregcaporaso** [comment]
I did some testing to confirm that both paths through the code work via the command line.

**Comment by gregcaporaso** [comment]
Thanks for the fix @mlangill, and for testing the release candidate!

**Comment by ekopylova** [comment]
I used two files (10000 and 10000000) of random sequences from the global gut. The following tests passed with success using pick_open_reference_otus.py -m sortmerna_sumaclust:

1. default --minimum_failure_threshold 100000
(a) 10000.fasta: (943 failures) skips steps 2,3
(b) 10000000.fasta: (967538 failures) goes through all steps 1-4

2. set --minimum_failure_threshold 900
(a) 10000.fasta: (943 failures) goes through steps all 1-4

Also, unit tests / script usages tests for pick_open_reference_otus.py passed locally.

**Comment by gregcaporaso** [comment]
Thank you @ekopylova!

**Comment by mlangill** [comment]
Great! Thanks for integrating this fix so quickly. Also, nice work on integrating new open source tools for OTU picking!

**Pull request merged**
