### PR TITLE
Fix matplotlib version

### PR DESCRIPTION
**Pull request by bgruening**
This should address https://github.com/biocore/qiime/issues/2117 and https://github.com/bioconda/bioconda-recipes/issues/945

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by jairideout** [comment]
ok to test

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1705/

**Comment by tacaswell** [comment]
(sorry for posting both here an on issue)

As a mpl dev :-1:  this is the wrong fix.  Using the same artist object between multiple figures has never been supported, if it looks like it was ever working it was coincidence.

**Comment by gregcaporaso** [comment]
Thanks for the contribution @bgruening. We're going to close this in favor of @tacaswell's pull request which fixed the broken code.

**Pull request closed without merging**
