### PR TITLE
add taxonomy to DESeq2 normalize table

### PR DESCRIPTION
**Pull request by sowe9385**

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1634/

**Comment by gregcaporaso** [comment]
retest this please

**Comment by gregcaporaso** [comment]
@sowe9385, can you please add some description of this change as well as a test case that would catch the error and a link back to the issue where we were discussing this?

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1635/

**Comment by sowe9385** [comment]
Issue #1929
<https://github.com/biocore/qiime/issues/1929#issuecomment-73072084>
Description:
'Taxonomy from DESeq normalized table was left off, because DESeq results
should not be used for anything but PCoA and heatmaps.  This was because of
the concern about the unresolved issue of DESeq's negatives/rare species
treatment leading to possible incorrect taxonomy plots, for example. Added
it back on to resemble input OTU table'

It is not a bug, and was done deliberately - so not sure we need a test.
And, if we add a test, it will fail due to the R package NA issue.

**Comment by jairideout** [comment]
@sowe9385 I tested out your changes and the resulting taxonomy looks like:

```
 "taxonomy": "c(\"Root\", \"k__Bacteria\", \"p__Firmicutes\", \"c__Bacilli\", \"o__Bacillales\", \"f__Staphylococcaceae\")"
```

This doesn't match the taxonomy format used in QIIME, so QIIME scripts that are taxonomy-aware won't work with these tables. The correct format should be:

```
"taxonomy": ["Root", "k__Bacteria", "p__Firmicutes", "c__Bacilli", "o__Bacillales", "f__Staphylococcaceae"]
```

Is it possible to have the output taxonomy match this format?

**Comment by jairideout** [comment]
In the interest of time, @gregcaporaso and I decided to *not* include taxonomy metadata in normalized tables because the taxonomy metadata is mis-formatted for both DESeq2 and CSS, and it won't work with taxonomy-aware QIIME scripts.

I'm closing this PR and will issue a new one shortly that removes taxonomy from CSS-normalized tables as well. That PR will also describe a workaround in normalize_table.py if users want to add taxonomy metadata to their normalized tables after the fact (i.e., using `biom add-metadata`).

**Pull request closed without merging**
