### PR TITLE
QIIME 1.9.0-rc2 bug fixes

### LINKED ISSUE #1850: numpy deprecation warnings
@wasade noted in #1847 that there are numpy deprecation warnings being raised with numpy 1.9.1:

```
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2499: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
Error in validate_mapping_file.py: option -m: file does not exist: 'map.tsv'

If you need help with QIIME, see:
http://help.qiime.org
```

I think these warnings are coming from PyCogent beta diversity code. It's strange that the warnings are being raised in scripts that aren't related to beta diversty (e.g., validate_mapping_file.py). We should figure out how to suppress these warnings, or at least suppress them for scripts that aren't related to beta diversity.

Note: I'm not able to reproduce this locally with numpy 1.9.1.

### PR DESCRIPTION
**Pull request by jairideout**
Fixes #1850 #1856.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
@jairideout, this looks good. Do you want me to let the tests run or merge now?

**Comment by gregcaporaso** [comment]
I guess probably let them run, since we should test with this version of SciPy.

**Comment by jairideout** [comment]
It was already testing against the latest scipy (0.15.0) so I think we're good on that end. I was planning on pushing more fixes to this PR though, so let's wait on merging.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1527/

**Comment by jairideout** [comment]
@gregcaporaso ready for review/merge.

**Comment by gregcaporaso** [comment]
Looks good, thanks @jairideout!

**Pull request merged**
