### PR TITLE
Set OTU table type

### PR DESCRIPTION
**Pull request by nuada**
Simple fix for problem with loading OTU table using R biom package descibed in #1928.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by gregcaporaso** [comment]
ok to test

**Comment by wasade** [comment]
Hi @nuada, thanks for the PR!

This is a slightly tricky one, but I believe this resolves some of the incompatibility issues of BIOM 1.0 formatted tables produced by QIIME 1.9 with the R BIOM parser. This likely stems from relatively recent changes to BIOM. The reason this is tricky is that we cannot be assured that the table type is actually an OTU table at this point. However, pragmatically, I think that is okay here given that this is a change to `make_otu_table.py` (and `simsam.py` was originally targeted at OTUs). 

@nuada, out of curiosity, have you tested if tables that have been produced by downstream methods (e.g., `filter_samples_from_otu_table.py`) are valid tables for the R BIOM parser? I'm curious about the scope of the issue as it would be nice to resolve this all at once if there are other areas of code that might be implicated.

@gregcaporaso @jairideout, I'd be interested in your thoughts on this. Previously this code relied on I believe a default in BIOM. The downside is that we force a table type. It is possible that doing anything other than forcing the type will get ugly quick and we may want to table until qiime2.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1587/

**Comment by nuada** [comment]
Hi @wasade,

I've tested `core_diversity_analyses.py` and `make_otu_table.py`. Your suspicion was correct. I missed two scripts.
But otherwise generated BIOM files look fine and information about type is retained. 

If you plan to use different type in the future I created cleaner fix #1938. This approach will require change in just a single line. Or you can override default value when needed.

**Comment by wasade** [comment]
This seems reasonable to me given that we're limiting effort on QIIME 1.x. Will wait for merge until @gregcaporaso and/or @jairideout can weigh in.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1588/

**Comment by gregcaporaso** [comment]
I think we should force the table type here. Since biom is not currently doing anything fancy with this information, I think it makes the most sense.

**Comment by gregcaporaso** [comment]
@wasade, thoughts on whether we should go with the #1937 or #1938 solution here? I'm good with either, so if you have a preference could you close one in favor of the other?

**Comment by wasade** [comment]
Closing in favor of #1938

**Pull request closed without merging**
