### PR TITLE
Provide the possibility to split demultiplexed files by sample, allow…

### PR DESCRIPTION
**Pull request by zachcp**
…ing a per-sample fastq output.

I've pencilled out a solution for #2082 as follows:
1. add an option to flag demultiplexing
2. pass the sample_id from the seq_generator
3. use the sample_id and outputdir to write-append each sample-specific file
4. rename the file at the end.

Still need some work/test but wanted to know if this is of interest before spending too much time. I'd be happy to code up tests if you like the idea.

zach cp

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by walterst** [comment]
Hello Zach,

Can you clarify how this will function differently than the --store_demultiplexed_fastq option with split_libraries_fastq.py?

**Comment by zachcp** [comment]
hi @walterst,

the `store_demultiplexed_fastq` option outputs a single fastq file. This pull request extends split_libraries_fastq to output a fastq file for each sample.

**Comment by jairideout** [comment]
ok to test

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1673/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1674/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1675/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1677/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1678/

**Comment by gregcaporaso** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1718/

**Pull request closed without merging**
