### PR TITLE
MAINT/TST: dependency version cap; "fix" broken bootstrapped p-value test

### LINKED ISSUE #2078: test_otu_significance.py is failing in Travis
This is preventing the tests in #2077 from passing.

```python
======================================================================
FAIL: test_run_correlation_test (__main__.GroupedCorrelationTests)
Test run_correlation_test works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/workspace/qiime-github-pr/qiime/tests/test_otu_significance.py", line 893, in test_run_correlation_test
    assert_almost_equal(obs_pvals[:-1], exp_bootstrapped_pvals)
  File "/mnt/workspace/qiime-github-pr/anaconda/envs/test_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 474, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/mnt/workspace/qiime-github-pr/anaconda/envs/test_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/mnt/workspace/qiime-github-pr/anaconda/envs/test_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 20.0%)
 x: array([ 0.486,  0.046,  0.371,  0.882,  0.438])
 y: array([ 0.486,  0.046,  0.382,  0.882,  0.438])

----------------------------------------------------------------------
Ran 15 tests in 42.885s

FAILED (failures=1)
```

@jairideout did something change when the CI system went down over the weekend?

@wdwvt1 any ideas on this?

I've tried with a few different versions of numpy and scipy in my machine and I can't replicate this problem.

### PR DESCRIPTION
**Pull request by jairideout**
QIIME 1 is now in maintenance mode, so capping dependency versions that we don't control to avoid future breakage (e.g., in unit tests).

Fixes #2078.

### CODE REVIEW

**Comment by jairideout** [comment]
Before merging, verify the capped dependency versions are being tested against with Jenkins.

**Comment by gregcaporaso** [comment]
Good to merge when this passes (pending @jairideout's comment above).

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1710/

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1711/

**Comment by jairideout** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1712/

**Comment by jairideout** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1713/

**Comment by jairideout** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1714/

**Comment by jairideout** [comment]
@gregcaporaso this is ready for merge! I verified the correct dependency versions are being tested against.

**Comment by gregcaporaso** [comment]
Awesome! Thanks for wrapping it up - great to have the build finally back to passing!

**Pull request merged**
