### PR TITLE
improve doc for filter_fasta (--valid_states)

### PR DESCRIPTION
**Pull request by iugrina**
A simple improvement to filter_fasta doc to explain the format for valid_states.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by gregcaporaso** [comment]
ok to test

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1722/

**Comment by iugrina** [comment]
@gregcaporaso Hi, the checks have failed which is quite strange since I've changed only one string for in the doc part of the file :/

**Comment by gregcaporaso** [comment]
@iugrina, yes, this is unrelated. I'm going to rerun the tests anyway though (to see if it's a real issue or just a stochastic failure).

**Comment by gregcaporaso** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1723/

**Comment by iugrina** [comment]
@gregcaporaso merge?

**Comment by gregcaporaso** [comment]
Merged, thanks for the contribution (and the reminder) @iugrina!

**Pull request merged**
