### PR TITLE
several quick fixes

### LINKED ISSUE #1978: IPython 3.1 update
- [x] update minimal dependency in setup.py
- [ ] update and test tutorial notebooks

### LINKED ISSUE #1982: require matplotlib != 1.4.2
setup.py should be updated to exclude matplotlib 1.4.2 because the taxa summary area plots don't show up with this version (see #1799 for details). Older and newer versions seem to work.

### LINKED ISSUE #1991: count_seqs.py fails on empty fasta
```bash
$ ls -al in.fasta
-rw-r--r--  1 caporaso  staff  0 Apr 28 08:44 in.fasta
$ count_seqs.py -i in.fasta
Traceback (most recent call last):
  File "/Users/caporaso/.virtualenvs/qiime/bin/count_seqs.py", line 10, in <module>
    execfile(__file__)
  File "/Users/caporaso/Dropbox/code/Qiime/scripts/count_seqs.py", line 92, in <module>
    main()
  File "/Users/caporaso/Dropbox/code/Qiime/scripts/count_seqs.py", line 81, in main
    suppress_errors)
  File "/Users/caporaso/Dropbox/code/Qiime/scripts/count_seqs.py", line 54, in format_output
    (c[0][0], c[1], c[0][1], c[0][2]))
TypeError: float argument required, not NoneType
```

Just a formatting issue.

### PR DESCRIPTION
**Pull request by gregcaporaso**
fixes #1991
fixes #1982
fixes #1978 (but created #1997)

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1627/

**Comment by jairideout** [comment]
Ready for merge when tests pass!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1630/

**Comment by gregcaporaso** [comment]
@jairideout, this is ready for merge.

**Pull request merged**
