### PR TITLE
Update dataFiles.html

### PR DESCRIPTION
**Pull request by walterst**
Removed "most recent" text assocated with Silva 111 on the resource page.

### CODE REVIEW

**Comment by antgonza** [comment]
Why?

**Comment by walterst** [comment]
Because Silva 119 is the newest now.

**Comment by antgonza** [comment]
OK, thanks. When will that be ready? :smiley:

**Comment by walterst** [comment]
It's up at http://www.arb-silva.de/download/archive/qiime/
(next line of the page). It seems that the older versions, 104 and 108,
were taken down from the archive though, I'm going to ask if they can be
put back up.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1597/

**Pull request merged**
