### PR TITLE
QIIME 1.9.0-rc2

### LINKED ISSUE #1818: add note on addition of start_parallel_jobs_slurm.py to changelog, and highlight in release notes

### PR DESCRIPTION
**Pull request by gregcaporaso**
Fixes #1818.

### CODE REVIEW

**Comment by jairideout** [comment]
Ready for merge once tests pass!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1517/

**Comment by jairideout** [comment]
retest this please

**Comment by jairideout** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1518/

**Comment by jairideout** [comment]
sourceforge downloads are down... will retest this later once that's fixed.

**Comment by jairideout** [comment]
Closing in favor of #1846.

**Pull request closed without merging**
