### PR TITLE
DO NOT MERGE: testing against biom-format 2.1.5 release candidate

### PR DESCRIPTION
**Pull request by jairideout**
# DO NOT MERGE

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1684/

**Comment by jairideout** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1685/

**Comment by gregcaporaso** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1686/

**Comment by gregcaporaso** [comment]
closing as this now seems to be working.

**Pull request closed without merging**
