### PR TITLE
Differential abundance

### PR DESCRIPTION
**Pull request by sowe9385**
add taxonomy to output.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1545/

**Comment by jairideout** [comment]
@sowe9385 looks like a legitimate failure in the script usage examples

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1555/

**Comment by jairideout** [comment]
@sowe9385 thanks for this addition! Can you please add unit tests for a BIOM table without taxonomy metadata? Once that's added this is ready for merge.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1563/

**Comment by jairideout** [comment]
Thanks @sowe9385!

**Pull request merged**
