### PR TITLE
Fix documentation of split_libraries_fastq

### PR DESCRIPTION
**Pull request by colinbrislawn**
Fixed spelling errors in the example commands as noted by @adamrp here: biocore/qiime#1940 
Also added description of when / why you would use this script.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by jairideout** [comment]
ok to test

**Comment by colinbrislawn** [comment]
Sorry @jairideout I think I missed a step. I did not rebuild the html docs after I updated that rst file.

Let me do that now...

**Comment by jairideout** [comment]
We generally don't edit the script RST files directly since those are generated from the scripts themselves. Can you please move your edits to split_libraries_fastq.py?

**Comment by colinbrislawn** [comment]
Ah ok. I'll do that now.

Once I write this into the split_libraries_fastq.py interface file with the other documentation, how do I go about building and verifying the resulting documentation?

Sorry for the dumb questions.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1590/

**Comment by jairideout** [comment]
No worries, I don't think we have the doc building process described anywhere (normally one of the devs does this around release time). To generate RST from split_libraries_fastq.py and then build the HTML docs:

```
$ qcli_make_rst -i scripts/split_libraries_fastq.py -o doc/scripts/
$ make -C doc clean html
```

You can then open the docs locally in a web browser (e.g., `doc/_build/html/index.html`).

You'll need Sphinx installed to build the documentation (this isn't included in a base QIIME install). You can install it with pip:

```
$ pip install Sphinx
```

**Comment by colinbrislawn** [comment]
Thanks @jairideout,

I've installed Sphinx and qcli like this `pip install Sphinx qcli`, but I'm receiving an error. 

``` bash
qcli_make_rst -i scripts/split_libraries_fastq.py -o doc/scripts/
Traceback (most recent call last):
  File "/people/bris469/bin/anaconda/bin/qcli_make_rst", line 243, in <module>
    main()
  File "/people/bris469/bin/anaconda/bin/qcli_make_rst", line 114, in main
    raise ImportError, "Can't import %s" % filename
ImportError: Can't import split_libraries_fastq
```
Is this related? biocore/pyqi#17

Thank you for helping me understand this. I'm interested in improving qiime's documentation especially because it is a core part of my projects.

**Comment by jairideout** [comment]
Hmmm, haven't seen this error before. Can you send me the output from the following commands?

```
$ pwd
$ which split_libraries_fastq.py
$ print_qiime_config.py -t
```

**Pull request closed without merging**
