### PR TITLE
addresses #2117

### PR DESCRIPTION
**Pull request by gregcaporaso**
This is probably safer, and shouldn't prevent us from doing anything we want to do since we're in bug fix mode only on QIIME 1.

### CODE REVIEW

**Comment by wasade** [comment]
Want to restrict to < 1.5.0 in the event of a micro release in 1.4?

**Comment by gregcaporaso** [comment]
We could - I guess I was just thinking that we know this one works... I don't really have strong feelings on this.

**Comment by wasade** [comment]
Either has risk but given that 1.2.x 1.3.x and 1.4.x work, I suspect the
core issue stems from some api change isolated to >= 1.5 and thus unlikely
to backport. 1.4.x has a history already of micro releases too of which if
they continue to happen may be relevant

**Comment by gregcaporaso** [comment]
Ok, good point. I'll change it.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1696/

**Comment by tacaswell** [comment]
There will be no more 1.4.x mpl releases.

**Pull request closed without merging**
