### PR TITLE
changed default confidence threshold for Naive Bayes classifiers

### LINKED ISSUE #1766: update assign_taxonomy.py defaults with recommendations from tax assignment paper
I'm working on the paper right now, and we're really going to want to get these updates in to QIIME. Ideally, we'll have the pre-print posted on PeerJ before too long, I'll figure out how to proceed with this by this Friday as I'll have a better estimate of when the paper will be posted by then.

### PR DESCRIPTION
**Pull request by gregcaporaso**
Fixes #1766

### CODE REVIEW

**Comment by jairideout** [comment]
Ready for merge once tests pass!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1575/

**Comment by jairideout** [comment]
@gregcaporaso there are legitimate test failures

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1576/

**Pull request merged**
