### PR TITLE
quickfix URL for blast in non-conda install

### PR DESCRIPTION
**Pull request by colinbrislawn**
Folks on the forms have not been able to download legacy-blast because the download location has changed. See these threads:
- https://groups.google.com/forum/#!topic/qiime-forum/oneq4GTxXcQ 
- https://groups.google.com/forum/#!topic/qiime-forum/MkldTFcJbCU

Let me know if you have any suggestions.

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by jairideout** [comment]
Thanks for the fix @colinbrislawn! I tried pushing a couple of minor changes to your branch and messed up the commit history in this PR, sorry about that. I created another PR (#2196) with the changes.

There was a formatting issue with one of the RST links, and I made the diff only include broken link fixes instead of text changes. After #2196 is merged, I'll have to hotfix the live website so I'm trying to keep the diff as small as possible (we're trying to avoid a full doc rebuild).

Thanks again!

**Comment by colinbrislawn** [comment]
Thanks for troubleshooting my messy PR! I'm more used to markdown than reStructuredText, so I appreciate your help.

**Comment by jairideout** [comment]
No problem, thanks for your help @colinbrislawn!

**Pull request closed without merging**
