### PR TITLE
Improve error message in parse.py. Closes #2113

### LINKED ISSUE #2113: Improve error message when bad fastq file is passed.
In the [qiime-form](https://groups.google.com/forum/#!topic/qiime-forum/3_q2cFXrTeU), a user had trouble understanding this error. (They thought it was referring to their mapping file.)
>Non-header line passed as input. Header must start with '@'.

https://github.com/biocore/qiime/blob/c2b62a86100f08e26011a11587a8da60ccaf409a/qiime/parse.py#L38

### PR DESCRIPTION
**Pull request by colinbrislawn**

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1690/

**Comment by gregcaporaso** [comment]
retest this please

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1715/

**Comment by colinbrislawn** [comment]
This is probably my smallest PR. Thanks Greg. 
:shipit:

**Comment by gregcaporaso** [comment]
Thanks @colinbrislawn. Sorry for the long delay. The jenkins build is fixed now, which makes this easier (not that yours was a particularly hard one) - we just needed to figure out what was going on and have been focused on QIIME 2 (as you know...).

**Pull request merged**
