### PR TITLE
update version changes and fitZIG bug fix ChangeLog

### PR DESCRIPTION
**Pull request by sowe9385**

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Thanks for the fix @sowe9385. Can you add a description here of how you determined what the new expected value should be?

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1617/

**Comment by gregcaporaso** [comment]
@sowe9385, it looks like there is still a failure from ``test_differential_abundance.py``.

**Comment by sowe9385** [comment]
Should be better now sorry.  1.) Check that current configuration gives
same output as 'exp' (expected) output in the failing
test_differential_abundance.py
2.) Update R version and Bioconductor packages
3.) Again run the sample commands on the test .biom table in
test_differential_abundance.py and compare how output differs.

I also check with the authors to see if this is expected/they updated their
Bioconductor packages.  Thanks.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1618/

**Comment by gregcaporaso** [comment]
Thanks @sowe9385. It's really important that you confirm that this is expected. Did you confirm that if you run ``fitZIG.r`` directly that the new values that you have set in ``exp`` are what are generated by the ``fitZIG.r``. Have you done that? While unlikely, we need to confirm that an error isn't being introduced between the completion of ``fitZIG.r`` and returning those results to the user.

**Comment by gregcaporaso** [comment]
These commits are now rolled into #1986 with some additional changes that will make these tests less sensitive to changes in the underlying R code. Closing in favor of #1986.

**Comment by sowe9385** [comment]
Yes, tested fitZIG.r directly.

**Pull request closed without merging**
