### PR TITLE
BLD: SortMeRNA to build

### PR DESCRIPTION
**Pull request by wasade**
This adds SortMeRNA to the build. I was only able to do very quick tests on OSX (10.8) and Linux for this. As in, I only had time to do:

```python
>>> import setup
```

Which has the effect of triggering the build process. 

There are two outstanding issues that I cannot resolve prior to loosing internet:

- [x] There is a lot of compilation output going over stdout or stderr and it would be good to trap this
- [x] The SortMeRNA tarball is about 15MB. @ekopylova, would it be possible to produce a reduced tarball that we could host on `ftp.microbio.me`?

Additional testing would of course be useful. I _think_ this covers the range of systems and issues we'll encounter but I cannot be positive.

### CODE REVIEW

**Comment by ekopylova** [comment]
Yes, I can produce a reduced tarball that doesn't include the representative rRNA databases (used in metatranscriptomic filtering).

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1513/

**Comment by wasade** [comment]
stdout/stderr is now blocked. The reduced sortmerna tarball does not build properly, so this PR is not yet ready for final review

**Comment by wasade** [comment]
tgz looks good, thanks @ekopylova!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1521/

**Comment by gregcaporaso** [comment]
@wasade, is this now ready for final review?

**Comment by wasade** [comment]
Ya, sorry, thought I had flagged it earlier

**Comment by gregcaporaso** [comment]
It wasn't totally clear from the discussion, so I just wanted to confirm.

**Comment by wasade** [comment]
No worries, I totally spaced the message :)

**Comment by jairideout** [comment]
Thanks @wasade! @gregcaporaso and I will issue a new pull request with your commits and some modifications (likely sometime today).

**Comment by jairideout** [comment]
Closing in favor of #1864.

**Pull request closed without merging**
