### PR TITLE
Update example in summarize_taxa.py

### PR DESCRIPTION
**Pull request by colinbrislawn**
As noted in this issue: biocore/qiime#2015
and this [post on the qiime forum](https://groups.google.com/forum/#!topic/qiime-forum/vKAfHuvr3fA).

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Can one of the admins verify this pull request?

**Comment by gregcaporaso** [comment]
ok to test

**Comment by gregcaporaso** [comment]
fixes #2015.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1638/

**Pull request merged**
