### PR TITLE
fix fitZIG

### PR DESCRIPTION
**Pull request by sowe9385**

### CODE REVIEW

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1606/

**Comment by antgonza** [comment]
Will it be worth adding a test with 10 and 75+ features?

**Comment by ElDeveloper** [comment]
Would also be good to add a note to the ChangeLog.

**Comment by sowe9385** [comment]
Don't think the 10 and 75 features will add anything, thanks.  These
techniques are not designed for small datasets, so the 10 features will
likely fail.
Sophie

**Comment by antgonza** [comment]
OK, what about adding a test making sure that they fail? Also, this
should be documented and validated on the script (if less than x
features, raise error) ...

**Comment by gregcaporaso** [comment]
We definitely need a change log mention for this.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1609/

**Comment by sowe9385** [comment]
Should this be merged now?  ChangeLog mention was added.  Tests with 10
features will not be relevant, since our OTU tables never have only 10
features.  Thanks!

**Pull request merged**
