### PR TITLE
1.9.1 quick fixes

### LINKED ISSUE #1979: pick_otus.py -s accepts values > 1
I tested this with sortmerna but guess the same issue exists for other picking methods. The issue is that you can pass -s 97 and an error is raised during the command creation vs. having it raise an error from pick_otus.py. For example
```
pick_otus.py -m sortmerna --sortmerna_tabular --sortmerna_best_N_alignments 100 -r databases/rest.fna -o sortmerna/rest -i splitLib/seqs.fna -s 50
Traceback (most recent call last):
  File "/Users/antoniog/.virtualenvs/platypus/bin/pick_otus.py", line 999, in <module>
    main()
  File "/Users/antoniog/.virtualenvs/platypus/bin/pick_otus.py", line 968, in main
    failure_path=failure_path)
  File "/Users/antoniog/.virtualenvs/platypus/lib/python2.7/site-packages/qiime/pick_otus.py", line 258, in __call__
    HALT_EXEC=False)
  File "/Users/antoniog/.virtualenvs/platypus/lib/python2.7/site-packages/bfillings/sortmerna_v2.py", line 397, in sortmerna_ref_cluster
    app_result = smr()
  File "/Users/antoniog/.virtualenvs/platypus/lib/python2.7/site-packages/burrito/util.py", line 302, in __call__
    result_paths)
  File "/Users/antoniog/.virtualenvs/platypus/lib/python2.7/site-packages/burrito/util.py", line 324, in _handle_app_result_build_failure
    raise ApplicationError("Error constructing CommandLineAppResult.")
burrito.util.ApplicationError: Error constructing CommandLineAppResult.
```

### LINKED ISSUE #1995: use tempfile.gettempdir in qiime.util.get_qiime_temp_dir
Also update codebase to use `get_qiime_temp_dir` instead of `/tmp`.

### PR DESCRIPTION
**Pull request by jairideout**
Fixes #1995. Fixes #1979.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Ready for merge when the tests pass.

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1628/

**Comment by jairideout** [comment]
@gregcaporaso I fixed the merge conflicts in the changelog. This is ready for merge, no need to let the tests run again.

**Comment by gregcaporaso** [comment]
Merged, thanks!

**Comment by qiime-r2d2** [comment]
Build results will soon be (or already are) available at: http://ci.qiime.org/job/qiime-github-pr/1631/

**Pull request merged**
